server:
  port: 8888

spring:
  datasource:
    username: signlang
    password: signlang123456
    url: jdbc:mysql://bewcf.info:3306/signlang?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com:
      example:
        mapper : debug